### ISSUE TITLE
Do we want this taxon?

### ISSUE THREAD

**Issue by eparejatobes** [era7bio/db.rna18S#1]
- http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=148771&lvl=2&lin=f&keep=1&srchmode=1&unlock

@rtobes please check

**Comment by rtobes** [comment]
¿?

**Comment by eparejatobes** [comment]
I want my "unidentified amoeba from potato", coming from Dublin!
